/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: StarWars-Universe (https://sketchfab.com/SWU)
license: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
source: https://sketchfab.com/3d-models/bb8-animated-15db7644c5b645f195f4d2dc0c5154ec
title: BB8 (Animated)
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/bb8.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.69}>
          <group name="3924ee77ba9a46c58a2abc9fdcf9971cfbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="BB8BB8" scale={0}>
                  <group name="BB8Center_NeutralPose" position={[0, 62, 0]}>
                    <group name="BB8Center">
                      <group name="BB8BB8_Body">
                        <mesh name="BB8BB8_Body_Scene_Material_0" geometry={nodes.BB8BB8_Body_Scene_Material_0.geometry} material={materials.Scene_Material} />
                        <mesh name="BB8BB8_Body_Scene_Material_0_1" geometry={nodes.BB8BB8_Body_Scene_Material_0_1.geometry} material={materials.Scene_Material} />
                      </group>
                      <group name="BB8Hatch_Door">
                        <mesh name="BB8Hatch_Door_Scene_Material_0" geometry={nodes.BB8Hatch_Door_Scene_Material_0.geometry} material={materials.Scene_Material} />
                      </group>
                    </group>
                  </group>
                  <group name="BB8Center_Head_NeutralPose" position={[0, 62, 0]}>
                    <group name="BB8Center_Head">
                      <group name="BB8Antena">
                        <mesh name="BB8Antena_Scene_Material1_0" geometry={nodes.BB8Antena_Scene_Material1_0.geometry} material={materials.Scene_Material1} />
                      </group>
                      <group name="BB8BB8_Head">
                        <mesh name="BB8BB8_Head_Scene_Material1_0" geometry={nodes.BB8BB8_Head_Scene_Material1_0.geometry} material={materials.Scene_Material1} />
                        <mesh name="BB8BB8_Head_Scene_Material1_0_1" geometry={nodes.BB8BB8_Head_Scene_Material1_0_1.geometry} material={materials.Scene_Material1} />
                      </group>
                      <group name="BB8Eye">
                        <mesh name="BB8Eye_Eye_0" geometry={nodes.BB8Eye_Eye_0.geometry} material={materials.material} />
                      </group>
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/bb8.gltf')
